version: '3.7'

services:
    development-client:
        build:
            context: .
            target: development-base
        ports:
            - '4200:4200'
        command: sh -c "ng serve --host 0.0.0.0 --poll=1000"
        tty: true
        volumes:
            - .:/home/node/sotetsu-lab-v3-client
            - nodemodules:/home/node/sotetsu-lab-v3-client/node_modules
        networks:
            - development-network

volumes:
    nodemodules:

networks:
    development-network:
